name: Test Astra App
on: push
jobs:  
  mytest:
    runs-on: ubuntu-latest
    steps: 
      - name: Get repo code
        uses: actions/checkout@v3.4.0
      - name: Install Deps
        run: npm ci 
      - name: Test App
        run: npm run testgit